services:
  - type: web
    name: sg-transport
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    healthCheckPath: /api/transport/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: LTA_API_KEY
        sync: false
