apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sg-transport
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/g3l00/sg-transport.git
    targetRevision: main
    path: k8s
    directory:
      exclude: application.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sg-transport
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
